config/routes.rb
Beerboard::Application.routes.draw do
  resources :breweries

  resources :dispenses

  resources :styles

  resources :beers

  resources :lines
  
  resources :beerlines

  resources :webviews

  

end

app/models/line.rb
class Line < ActiveRecord::Base
  belongs_to :dispense
  belongs_to :beer
  after_save :assign_beer_to_line
  
  
  def currentBeer
    if (beer_id)
      cb = Beer.find(beer_id)
    else
      cb =Beer.new
      cb.brewery = Brewery.new
      cb.style = Style.new
    end
    return cb
  end
  
  #once a beer as been assigned to a line then decrease the available stock
  #of that beer by one
  def assign_beer_to_line
    if (beer_id)
      beer = Beer.find(beer_id)
      previous_stock = beer.stock
      beer.stock = previous_stock -1
      beer.save
    end
  end
  
  

  
  
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  before_filter :authenticate
  before_action :set_line, only: [:show, :edit, :update, :destroy]


  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
        username == "foo" && password == "bar"
      end
  end
  

  # GET /lines
  # GET /lines.json
  def index
    @lines = Line.order("number")
  end

  # GET /lines/1
  # GET /lines/1.json
  def show
  end

  # GET /lines/new
  def new
    @line = Line.new
  end

  # GET /lines/1/edit
  def edit
  end

  # POST /lines
  # POST /lines.json
  def create
    @line = Line.new(line_params)

    respond_to do |format|
      if @line.save
        format.html { redirect_to @line, notice: 'Line was successfully created.' }
        format.json { render action: 'show', status: :created, location: @line }
      else
        format.html { render action: 'new' }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lines/1
  # PATCH/PUT /lines/1.json
  def update
    respond_to do |format|
      if @line.update(line_params)
        format.html { redirect_to @line, notice: 'Line was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lines/1
  # DELETE /lines/1.json
  def destroy
    @line.destroy
    respond_to do |format|
      format.html { redirect_to lines_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line
      @line = Line.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_params
      params.require(:line).permit(:number, :name, :dispense_id, :beer_id)
    end
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/views/lines/_changebeer.html.erb
<%= simple_form_for(@line) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    Current Beer is <%= @line.currentBeer.name %>
    <%= f.association :beer, collection: Beer.available(@line.dispense_id) %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lines/_form.html.erb
<%= simple_form_for(@line) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :number %>
    <%= f.input :name %>
    <%= f.association :dispense %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lines/edit.html.erb
<h1>Change Beer on <%=@line.name%></h1>
<hr>

<%= render 'changebeer' %>

<%= link_to 'Show', @line %> |
<%= link_to 'Back', lines_path %>

app/views/lines/index.html.erb
<h1>Change Beer Console</h1>
<hr>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Line Name</th>
      <th>Beer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @lines.each do |line| %>
      <tr>
        <td><%= line.number %></td>
        <td><%= line.name %></td>
        <td><%= line.currentBeer.name %></td>
        <td><%= link_to 'Beer Change', edit_line_path(line) %></td>
        <td><%= link_to 'Destroy', line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line', new_line_path %>

app/views/lines/new.html.erb
<h1>New line</h1>

<%= render 'form' %>

<%= link_to 'Back', lines_path %>

app/views/lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @line.number %>
</p>

<p>
  <strong>Name:</strong>
  <%= @line.name %>
</p>

<p>
  <strong>Dispense:</strong>
  <%= @line.dispense.name %>
</p>

<p>
  <strong>Beer:</strong>
  <%= @line.currentBeer.name %>
</p>

<p>
	<strong>Pump Clip:</strong>
	<%= image_tag "#{@line.currentBeer.pumpclip}", height: '55', width: 'auto' %>
</p>
<%= link_to 'Edit', edit_line_path(@line) %> |
<%= link_to 'Back', lines_path %>