config/routes.rb
Beerboard::Application.routes.draw do
  resources :breweries

  resources :dispenses

  resources :styles

  resources :beers

  resources :lines
  
  resources :beerlines

  resources :webviews

  

end

app/models/style.rb
class Style < ActiveRecord::Base
  has_many :beers
  
  def to_s
    'Testing'
  end
  
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :set_style, only: [:show, :edit, :update, :destroy]

  # GET /styles
  # GET /styles.json
  def index
    @styles = Style.all
  end

  # GET /styles/1
  # GET /styles/1.json
  def show
  end

  # GET /styles/new
  def new
    @style = Style.new
  end

  # GET /styles/1/edit
  def edit
  end

  # POST /styles
  # POST /styles.json
  def create
    @style = Style.new(style_params)

    respond_to do |format|
      if @style.save
        format.html { redirect_to @style, notice: 'Style was successfully created.' }
        format.json { render action: 'show', status: :created, location: @style }
      else
        format.html { render action: 'new' }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /styles/1
  # PATCH/PUT /styles/1.json
  def update
    respond_to do |format|
      if @style.update(style_params)
        format.html { redirect_to @style, notice: 'Style was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /styles/1
  # DELETE /styles/1.json
  def destroy
    @style.destroy
    respond_to do |format|
      format.html { redirect_to styles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_style
      @style = Style.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def style_params
      params.require(:style).permit(:name, :image)
    end
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/_form.html.erb
<%= simple_form_for(@style) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :name %>
    <%= f.input :image %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/styles/edit.html.erb
<h1>Editing style</h1>

<%= render 'form' %>

<%= link_to 'Show', @style %> |
<%= link_to 'Back', styles_path %>

app/views/styles/index.html.erb
<h1>Listing styles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @styles.each do |style| %>
      <tr>
        <td><%= style.name %></td>
        <td><%= style.image %></td>
        <td><%= link_to 'Show', style %></td>
        <td><%= link_to 'Edit', edit_style_path(style) %></td>
        <td><%= link_to 'Destroy', style, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Style', new_style_path %>

app/views/styles/new.html.erb
<h1>New style</h1>

<%= render 'form' %>

<%= link_to 'Back', styles_path %>

app/views/styles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @style.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @style.image %>
</p>

<%= link_to 'Edit', edit_style_path(@style) %> |
<%= link_to 'Back', styles_path %>