config/routes.rb
Beerboard::Application.routes.draw do
  resources :breweries

  resources :dispenses

  resources :styles

  resources :beers

  resources :lines
  
  resources :beerlines

  resources :webviews

  

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  belongs_to :brewery
  belongs_to :style
  belongs_to :dispense
 
  validates :name, presence: true
  validates :brewery, presence: true
  validates :style, presence: true
  validates :dispense, presence: true

  
   
  def self.available(dispense_id)
    Beer.where("stock > 0 and dispense_id = #{dispense_id}")
    #Beer.where("stock > 0")
  end
  
  #To Do tidy up so it is not hard wired to a dispense id
  def self.nextOnCask()
    puts("*************In Next On Cask************")
    beers = Beer.where("stock > 0 and dispense_id =1").limit(4)
    puts ("Number of beers returned #{beers.size}")
    return beers
    
  end
  
   #To Do tidy up so it is not hard wired to a dispense id
  def self.nextOnKeg()
    Beer.where("stock > 0 and dispense_id =2").limit(4)
  end
  
  
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]

  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.order("brewery_id")
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
  end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, notice: 'Beer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @beer }
      else
        format.html { render action: 'new' }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:name, :abv, :pumpclip, :cost, :stock, :price_per_pint, :price_one, :price_two, :price_one_description, :price_two_description, :style_id, :brewery_id, :dispense_id, :description)
    end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.erb
<%= simple_form_for(@beer) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :name %>
    <%= f.input :abv %>
    <%= f.input :stock %>
    <%= f.input :price_one %>
	<%= f.input :price_two %>
	<%= f.input :price_one_description %>
	<%= f.input :price_two_description %>
    <%= f.association :style%>
    <%= f.association :brewery %>
    <%= f.association :dispense %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<h1>Beers</h1>
<hr>

<table>
  <thead>
    <tr>
      <th>Brewery</th>
      <th>Name</th>
      <th>ABV</th>
      <th>Stock</th>
      <th>Style</th>
      <th>Dispense</th>
    </tr>
  </thead>

  <tbody>
    <% @beers.each do |beer| %>
      <tr>
        <td><%= link_to beer.brewery.name, edit_beer_path(beer) %></td>
        <td><%= beer.name %></td>
        <td><%= number_to_percentage(beer.abv, precision: 1)%></td>
        <td><%= beer.stock %></td>
		<% if beer.style %>
        	<td><%= beer.style.name %></td>
		<% end %>
        <td><%= beer.dispense.name %></td>
        <td><%= link_to 'Edit', edit_beer_path(beer) %></td>
        <td><%= link_to 'Destroy', beer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stuff', new_beer_path %>

app/views/beers/new.html.erb
<h1>New beer</h1>

<%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @beer.name %>
</p>

<p>
  <strong>Abv:</strong>
  <%= @beer.abv %>
</p>

<p>
  <strong>Pumpclip:</strong>
  <%= @beer.pumpclip %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @beer.cost %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @beer.stock %>
</p>

<p>
  <strong>Price per pint:</strong>
  <%= @beer.price_per_pint %>
</p>

<p>
  <strong>Style:</strong>
  <%= @beer.style %>
</p>

<p>
  <strong>Brewery:</strong>
  <%= @beer.brewery %>
</p>

<p>
  <strong>Dispense:</strong>
  <%= @beer.dispense.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @beer.description %>
</p>

<%= link_to 'Edit', edit_beer_path(@beer) %> |
<%= link_to 'Back', beers_path %>